// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gLiter.Infrastructure.Data;

#nullable disable

namespace gLiter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228064649_SeedAllDefaultData")]
    partial class SeedAllDefaultData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gLiter.Core.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByName = "",
                            Email = "superadmin@g-liter.com",
                            FullName = "Super Admin",
                            IsActive = true,
                            IsPrimary = false,
                            PasswordHash = new byte[] { 163, 156, 132, 218, 88, 224, 47, 158, 0, 71, 188, 7, 25, 198, 43, 39, 216, 196, 107, 106, 80, 100, 179, 117, 125, 44, 209, 217, 45, 251, 219, 130, 63, 237, 6, 216, 95, 89, 15, 63, 122, 24, 254, 23, 131, 234, 45, 94, 141, 198, 241, 125, 31, 118, 113, 98, 26, 1, 130, 168, 38, 184, 172, 210 },
                            PasswordSalt = new byte[] { 95, 56, 239, 211, 56, 115, 125, 202, 54, 137, 126, 99, 97, 3, 148, 183, 114, 192, 53, 166, 177, 236, 220, 179, 132, 123, 202, 184, 154, 55, 45, 208, 95, 112, 253, 60, 193, 113, 189, 226, 197, 183, 34, 105, 44, 61, 100, 234, 220, 241, 13, 105, 113, 253, 176, 5, 112, 205, 73, 17, 123, 31, 185, 88, 28, 112, 200, 206, 174, 178, 112, 225, 126, 68, 76, 99, 255, 4, 227, 172, 45, 31, 80, 8, 81, 139, 81, 225, 216, 84, 40, 132, 190, 181, 86, 255, 166, 128, 215, 17, 177, 162, 8, 88, 232, 18, 164, 239, 155, 141, 90, 244, 99, 66, 83, 235, 81, 153, 214, 44, 235, 17, 5, 195, 12, 126, 35, 11 },
                            Role = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByName = "",
                            Email = "cs@g-liter.com",
                            FullName = "Customer Service",
                            IsActive = true,
                            IsPrimary = false,
                            PasswordHash = new byte[] { 163, 156, 132, 218, 88, 224, 47, 158, 0, 71, 188, 7, 25, 198, 43, 39, 216, 196, 107, 106, 80, 100, 179, 117, 125, 44, 209, 217, 45, 251, 219, 130, 63, 237, 6, 216, 95, 89, 15, 63, 122, 24, 254, 23, 131, 234, 45, 94, 141, 198, 241, 125, 31, 118, 113, 98, 26, 1, 130, 168, 38, 184, 172, 210 },
                            PasswordSalt = new byte[] { 95, 56, 239, 211, 56, 115, 125, 202, 54, 137, 126, 99, 97, 3, 148, 183, 114, 192, 53, 166, 177, 236, 220, 179, 132, 123, 202, 184, 154, 55, 45, 208, 95, 112, 253, 60, 193, 113, 189, 226, 197, 183, 34, 105, 44, 61, 100, 234, 220, 241, 13, 105, 113, 253, 176, 5, 112, 205, 73, 17, 123, 31, 185, 88, 28, 112, 200, 206, 174, 178, 112, 225, 126, 68, 76, 99, 255, 4, 227, 172, 45, 31, 80, 8, 81, 139, 81, 225, 216, 84, 40, 132, 190, 181, 86, 255, 166, 128, 215, 17, 177, 162, 8, 88, 232, 18, 164, 239, 155, 141, 90, 244, 99, 66, 83, 235, 81, 153, 214, 44, 235, 17, 5, 195, 12, 126, 35, 11 },
                            Role = "CustomerService",
                            Username = "cs_admin"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByName = "",
                            Email = "hr@g-liter.com",
                            FullName = "HR Manager",
                            IsActive = true,
                            IsPrimary = false,
                            PasswordHash = new byte[] { 163, 156, 132, 218, 88, 224, 47, 158, 0, 71, 188, 7, 25, 198, 43, 39, 216, 196, 107, 106, 80, 100, 179, 117, 125, 44, 209, 217, 45, 251, 219, 130, 63, 237, 6, 216, 95, 89, 15, 63, 122, 24, 254, 23, 131, 234, 45, 94, 141, 198, 241, 125, 31, 118, 113, 98, 26, 1, 130, 168, 38, 184, 172, 210 },
                            PasswordSalt = new byte[] { 95, 56, 239, 211, 56, 115, 125, 202, 54, 137, 126, 99, 97, 3, 148, 183, 114, 192, 53, 166, 177, 236, 220, 179, 132, 123, 202, 184, 154, 55, 45, 208, 95, 112, 253, 60, 193, 113, 189, 226, 197, 183, 34, 105, 44, 61, 100, 234, 220, 241, 13, 105, 113, 253, 176, 5, 112, 205, 73, 17, 123, 31, 185, 88, 28, 112, 200, 206, 174, 178, 112, 225, 126, 68, 76, 99, 255, 4, 227, 172, 45, 31, 80, 8, 81, 139, 81, 225, 216, 84, 40, 132, 190, 181, 86, 255, 166, 128, 215, 17, 177, 162, 8, 88, 232, 18, 164, 239, 155, 141, 90, 244, 99, 66, 83, 235, 81, 153, 214, 44, 235, 17, 5, 195, 12, 126, 35, 11 },
                            Role = "HR",
                            Username = "hr_admin"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrivacyPolicyAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("gLiter.Core.Models.FleetVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FleetVehicles");
                });

            modelBuilder.Entity("gLiter.Core.Models.FuelPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FuelPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "سعر لتر بنزين 80",
                            DescriptionEn = "Gasoline 80 price per liter",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Gasoline80",
                            Price = 12.25m,
                            TitleAr = "بنزين 80",
                            TitleEn = "Gasoline 80"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "سعر لتر بنزين 92",
                            DescriptionEn = "Gasoline 92 price per liter",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Gasoline92",
                            Price = 13.75m,
                            TitleAr = "بنزين 92",
                            TitleEn = "Gasoline 92"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "سعر لتر بنزين 95",
                            DescriptionEn = "Gasoline 95 price per liter",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Gasoline95",
                            Price = 15.00m,
                            TitleAr = "بنزين 95",
                            TitleEn = "Gasoline 95"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "سعر لتر السولار",
                            DescriptionEn = "Diesel price per liter",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            Price = 10.00m,
                            TitleAr = "سولار",
                            TitleEn = "Diesel"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GalleryImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "صورة لمحطة الوقود الرئيسية في القاهرة",
                            DescriptionEn = "Photo of the main fuel station in Cairo",
                            ImageUrl = "/images/gallery/station-1.jpg",
                            TitleAr = "محطة الوقود الرئيسية",
                            TitleEn = "Main Fuel Station"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "جزء من أسطول نقل الوقود الحديث",
                            DescriptionEn = "Part of our modern fuel transport fleet",
                            ImageUrl = "/images/gallery/fleet-1.jpg",
                            TitleAr = "أسطول النقل",
                            TitleEn = "Transport Fleet"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "فريق العمل المحترف في جي ليتر",
                            DescriptionEn = "Professional team at G-Liter",
                            ImageUrl = "/images/gallery/team-1.jpg",
                            TitleAr = "فريق العمل",
                            TitleEn = "Our Team"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "أحدث معدات السلامة المستخدمة",
                            DescriptionEn = "Latest safety equipment in use",
                            ImageUrl = "/images/gallery/safety-1.jpg",
                            TitleAr = "معدات السلامة",
                            TitleEn = "Safety Equipment"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.HeroSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HeroSections");
                });

            modelBuilder.Entity("gLiter.Core.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "مطلوب سائق صهريج وقود بخبرة لا تقل عن 3 سنوات. رخصة قيادة مهنية درجة أولى.",
                            DescriptionEn = "Fuel tanker driver needed with minimum 3 years experience. First class professional driving license required.",
                            ExpiresAt = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Cairo, Egypt",
                            PostedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "سائق صهريج وقود",
                            TitleEn = "Fuel Tanker Driver"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "فني صيانة للعمل في محطات الوقود. خبرة في صيانة المعدات الميكانيكية والكهربائية.",
                            DescriptionEn = "Maintenance technician for fuel stations. Experience in mechanical and electrical equipment maintenance.",
                            ExpiresAt = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Alexandria, Egypt",
                            PostedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "فني صيانة محطات",
                            TitleEn = "Station Maintenance Technician"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محاسب للعمل في المقر الرئيسي. بكالوريوس تجارة وخبرة لا تقل عن سنتين.",
                            DescriptionEn = "Accountant for head office. Commerce degree with minimum 2 years experience.",
                            ExpiresAt = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Cairo, Egypt",
                            PostedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "محاسب",
                            TitleEn = "Accountant"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "تم افتتاح محطة وقود جديدة في منطقة التجمع الخامس لخدمة سكان المنطقة بأعلى معايير الجودة.",
                            DescriptionEn = "A new fuel station has been opened in the Fifth Settlement area to serve residents with the highest quality standards.",
                            ImageUrl = "/images/news/new-station.jpg",
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "افتتاح محطة وقود جديدة",
                            TitleEn = "New Fuel Station Opening"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "تم تحديث أسعار الوقود وفقاً للأسعار العالمية. الأسعار الجديدة سارية من اليوم.",
                            DescriptionEn = "Fuel prices have been updated according to global prices. New prices are effective from today.",
                            ImageUrl = "/images/news/prices-update.jpg",
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "تحديث أسعار الوقود",
                            TitleEn = "Fuel Prices Update"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "توقيع اتفاقية شراكة استراتيجية مع كبرى شركات الطاقة لتوسيع نطاق خدماتنا.",
                            DescriptionEn = "Signing a strategic partnership agreement with major energy companies to expand our services.",
                            ImageUrl = "/images/news/partnership.jpg",
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "شراكة استراتيجية جديدة",
                            TitleEn = "New Strategic Partnership"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "خدمة نقل الوقود بأعلى معايير الأمان والجودة إلى جميع المحطات",
                            DescriptionEn = "Fuel transportation service with the highest safety and quality standards to all stations",
                            IconUrl = "/images/services/fuel-transport.svg",
                            TitleAr = "نقل الوقود",
                            TitleEn = "Fuel Transportation"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "إدارة شاملة لمحطات الوقود تشمل الصيانة والتشغيل",
                            DescriptionEn = "Comprehensive fuel station management including maintenance and operations",
                            IconUrl = "/images/services/station-management.svg",
                            TitleAr = "إدارة المحطات",
                            TitleEn = "Station Management"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "إدارة وصيانة أسطول النقل بأحدث التقنيات",
                            DescriptionEn = "Fleet management and maintenance with the latest technologies",
                            IconUrl = "/images/services/fleet.svg",
                            TitleAr = "خدمات الأسطول",
                            TitleEn = "Fleet Services"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "استشارات متخصصة في قطاع الطاقة والوقود",
                            DescriptionEn = "Specialized consulting in the energy and fuel sector",
                            IconUrl = "/images/services/consulting.svg",
                            TitleAr = "الاستشارات",
                            TitleEn = "Consulting"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "شارع عباس العقاد، مدينة نصر",
                            City = "Cairo",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة وقود متكاملة الخدمات في قلب مدينة نصر",
                            DescriptionEn = "Full-service fuel station in the heart of Nasr City",
                            Latitude = 30.0626,
                            Longitude = 31.345600000000001,
                            Phone = "+20 2 1234567",
                            TitleAr = "محطة مدينة نصر",
                            TitleEn = "Nasr City Station"
                        },
                        new
                        {
                            Id = 2,
                            Address = "شارع التسعين، التجمع الخامس",
                            City = "Cairo",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة حديثة في التجمع الخامس مع خدمات متميزة",
                            DescriptionEn = "Modern station in Fifth Settlement with premium services",
                            Latitude = 30.007400000000001,
                            Longitude = 31.491299999999999,
                            Phone = "+20 2 2345678",
                            TitleAr = "محطة التجمع الخامس",
                            TitleEn = "Fifth Settlement Station"
                        },
                        new
                        {
                            Id = 3,
                            Address = "طريق الكورنيش، الإسكندرية",
                            City = "Alexandria",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة وقود رئيسية في الإسكندرية",
                            DescriptionEn = "Main fuel station in Alexandria",
                            Latitude = 31.200099999999999,
                            Longitude = 29.918700000000001,
                            Phone = "+20 3 3456789",
                            TitleAr = "محطة الإسكندرية",
                            TitleEn = "Alexandria Station"
                        },
                        new
                        {
                            Id = 4,
                            Address = "المحور المركزي، 6 أكتوبر",
                            City = "Giza",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة متكاملة في مدينة 6 أكتوبر",
                            DescriptionEn = "Integrated station in 6th October City",
                            Latitude = 29.9285,
                            Longitude = 30.918800000000001,
                            Phone = "+20 2 4567890",
                            TitleAr = "محطة 6 أكتوبر",
                            TitleEn = "6th October Station"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.SuccessPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SuccessPartners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريك استراتيجي في توريد الوقود",
                            DescriptionEn = "Strategic partner in fuel supply",
                            LogoUrl = "/images/partners/npc-logo.png",
                            TitleAr = "شركة البترول الوطنية",
                            TitleEn = "National Petroleum Company"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريك في مشاريع الطاقة المستدامة",
                            DescriptionEn = "Partner in sustainable energy projects",
                            LogoUrl = "/images/partners/rec-logo.png",
                            TitleAr = "شركة الطاقة المتجددة",
                            TitleEn = "Renewable Energy Co"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريك مالي واستثماري",
                            DescriptionEn = "Financial and investment partner",
                            LogoUrl = "/images/partners/ib-logo.png",
                            TitleAr = "بنك الاستثمار",
                            TitleEn = "Investment Bank"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريك في خدمات النقل واللوجستيات",
                            DescriptionEn = "Partner in transport and logistics services",
                            LogoUrl = "/images/partners/itc-logo.png",
                            TitleAr = "شركة النقل الدولية",
                            TitleEn = "International Transport Co"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.TransportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TransportRequests");
                });

            modelBuilder.Entity("gLiter.Core.Models.TransportRequestImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransportRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TransportRequestId");

                    b.ToTable("TransportRequestImages");
                });

            modelBuilder.Entity("gLiter.Core.Models.TransportRequestImage", b =>
                {
                    b.HasOne("gLiter.Core.Models.TransportRequest", "TransportRequest")
                        .WithMany("Images")
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportRequest");
                });

            modelBuilder.Entity("gLiter.Core.Models.TransportRequest", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
