// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gLiter.Infrastructure.Data;

#nullable disable

namespace gLiter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gLiter.Core.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByName = "",
                            Email = "superadmin@g-liter.com",
                            FullName = "Super Admin",
                            IsActive = true,
                            IsPrimary = false,
                            PasswordHash = new byte[] { 184, 199, 98, 33, 46, 122, 128, 39, 148, 234, 18, 151, 188, 131, 85, 117, 225, 116, 10, 211, 45, 78, 189, 36, 172, 137, 87, 235, 228, 61, 77, 37, 14, 110, 80, 65, 32, 247, 220, 22, 24, 25, 53, 226, 199, 2, 231, 57, 146, 131, 223, 82, 119, 124, 107, 29, 62, 234, 57, 4, 12, 150, 142, 167 },
                            PasswordSalt = new byte[] { 42, 75, 159, 104, 99, 209, 99, 110, 185, 201, 193, 79, 172, 226, 31, 18, 103, 108, 109, 193, 230, 214, 120, 169, 170, 60, 22, 254, 119, 241, 126, 94, 134, 211, 54, 64, 123, 3, 122, 193, 87, 131, 184, 190, 139, 206, 163, 236, 242, 12, 124, 118, 241, 51, 28, 170, 51, 104, 203, 121, 180, 214, 99, 178, 216, 219, 6, 163, 233, 69, 64, 19, 147, 123, 30, 18, 191, 47, 62, 163, 128, 97, 66, 45, 25, 2, 91, 40, 185, 232, 100, 249, 26, 186, 249, 209, 197, 110, 65, 158, 154, 54, 188, 55, 19, 97, 2, 10, 172, 188, 78, 223, 43, 218, 206, 238, 88, 174, 63, 232, 111, 31, 157, 73, 176, 228, 161, 103 },
                            Role = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByName = "",
                            Email = "cs@g-liter.com",
                            FullName = "Customer Service",
                            IsActive = true,
                            IsPrimary = false,
                            PasswordHash = new byte[] { 184, 199, 98, 33, 46, 122, 128, 39, 148, 234, 18, 151, 188, 131, 85, 117, 225, 116, 10, 211, 45, 78, 189, 36, 172, 137, 87, 235, 228, 61, 77, 37, 14, 110, 80, 65, 32, 247, 220, 22, 24, 25, 53, 226, 199, 2, 231, 57, 146, 131, 223, 82, 119, 124, 107, 29, 62, 234, 57, 4, 12, 150, 142, 167 },
                            PasswordSalt = new byte[] { 42, 75, 159, 104, 99, 209, 99, 110, 185, 201, 193, 79, 172, 226, 31, 18, 103, 108, 109, 193, 230, 214, 120, 169, 170, 60, 22, 254, 119, 241, 126, 94, 134, 211, 54, 64, 123, 3, 122, 193, 87, 131, 184, 190, 139, 206, 163, 236, 242, 12, 124, 118, 241, 51, 28, 170, 51, 104, 203, 121, 180, 214, 99, 178, 216, 219, 6, 163, 233, 69, 64, 19, 147, 123, 30, 18, 191, 47, 62, 163, 128, 97, 66, 45, 25, 2, 91, 40, 185, 232, 100, 249, 26, 186, 249, 209, 197, 110, 65, 158, 154, 54, 188, 55, 19, 97, 2, 10, 172, 188, 78, 223, 43, 218, 206, 238, 88, 174, 63, 232, 111, 31, 157, 73, 176, 228, 161, 103 },
                            Role = "CustomerService",
                            Username = "cs_admin"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByName = "",
                            Email = "hr@g-liter.com",
                            FullName = "HR Manager",
                            IsActive = true,
                            IsPrimary = false,
                            PasswordHash = new byte[] { 184, 199, 98, 33, 46, 122, 128, 39, 148, 234, 18, 151, 188, 131, 85, 117, 225, 116, 10, 211, 45, 78, 189, 36, 172, 137, 87, 235, 228, 61, 77, 37, 14, 110, 80, 65, 32, 247, 220, 22, 24, 25, 53, 226, 199, 2, 231, 57, 146, 131, 223, 82, 119, 124, 107, 29, 62, 234, 57, 4, 12, 150, 142, 167 },
                            PasswordSalt = new byte[] { 42, 75, 159, 104, 99, 209, 99, 110, 185, 201, 193, 79, 172, 226, 31, 18, 103, 108, 109, 193, 230, 214, 120, 169, 170, 60, 22, 254, 119, 241, 126, 94, 134, 211, 54, 64, 123, 3, 122, 193, 87, 131, 184, 190, 139, 206, 163, 236, 242, 12, 124, 118, 241, 51, 28, 170, 51, 104, 203, 121, 180, 214, 99, 178, 216, 219, 6, 163, 233, 69, 64, 19, 147, 123, 30, 18, 191, 47, 62, 163, 128, 97, 66, 45, 25, 2, 91, 40, 185, 232, 100, 249, 26, 186, 249, 209, 197, 110, 65, 158, 154, 54, 188, 55, 19, 97, 2, 10, 172, 188, 78, 223, 43, 218, 206, 238, 88, 174, 63, 232, 111, 31, 157, 73, 176, 228, 161, 103 },
                            Role = "HR",
                            Username = "hr_admin"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrivacyPolicyAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("gLiter.Core.Models.FleetVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FleetVehicles");
                });

            modelBuilder.Entity("gLiter.Core.Models.FuelPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FuelPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "سعر لتر بنزين 80",
                            DescriptionEn = "Gasoline 80 price per liter",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Gasoline80",
                            Price = 12.25m,
                            TitleAr = "بنزين 80",
                            TitleEn = "Gasoline 80"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "سعر لتر بنزين 92",
                            DescriptionEn = "Gasoline 92 price per liter",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Gasoline92",
                            Price = 13.75m,
                            TitleAr = "بنزين 92",
                            TitleEn = "Gasoline 92"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "سعر لتر بنزين 95",
                            DescriptionEn = "Gasoline 95 price per liter",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Gasoline95",
                            Price = 15.00m,
                            TitleAr = "بنزين 95",
                            TitleEn = "Gasoline 95"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "سعر لتر السولار",
                            DescriptionEn = "Diesel price per liter",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelType = "Diesel",
                            Price = 10.00m,
                            TitleAr = "سولار",
                            TitleEn = "Diesel"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GalleryImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "صورة لمحطة الوقود الرئيسية في القاهرة",
                            DescriptionEn = "Photo of the main fuel station in Cairo",
                            ImageUrl = "/images/gallery/station-1.jpg",
                            TitleAr = "محطة الوقود الرئيسية",
                            TitleEn = "Main Fuel Station"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "جزء من أسطول نقل الوقود الحديث",
                            DescriptionEn = "Part of our modern fuel transport fleet",
                            ImageUrl = "/images/gallery/fleet-1.jpg",
                            TitleAr = "أسطول النقل",
                            TitleEn = "Transport Fleet"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "فريق العمل المحترف في جي ليتر",
                            DescriptionEn = "Professional team at G-Liter",
                            ImageUrl = "/images/gallery/team-1.jpg",
                            TitleAr = "فريق العمل",
                            TitleEn = "Our Team"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "أحدث معدات السلامة المستخدمة",
                            DescriptionEn = "Latest safety equipment in use",
                            ImageUrl = "/images/gallery/safety-1.jpg",
                            TitleAr = "معدات السلامة",
                            TitleEn = "Safety Equipment"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.HeroSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HeroSections");
                });

            modelBuilder.Entity("gLiter.Core.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "مطلوب سائق صهريج وقود بخبرة لا تقل عن 3 سنوات. رخصة قيادة مهنية درجة أولى.",
                            DescriptionEn = "Fuel tanker driver needed with minimum 3 years experience. First class professional driving license required.",
                            ExpiresAt = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Cairo, Egypt",
                            PostedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "سائق صهريج وقود",
                            TitleEn = "Fuel Tanker Driver"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "فني صيانة للعمل في محطات الوقود. خبرة في صيانة المعدات الميكانيكية والكهربائية.",
                            DescriptionEn = "Maintenance technician for fuel stations. Experience in mechanical and electrical equipment maintenance.",
                            ExpiresAt = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Alexandria, Egypt",
                            PostedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "فني صيانة محطات",
                            TitleEn = "Station Maintenance Technician"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محاسب للعمل في المقر الرئيسي. بكالوريوس تجارة وخبرة لا تقل عن سنتين.",
                            DescriptionEn = "Accountant for head office. Commerce degree with minimum 2 years experience.",
                            ExpiresAt = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Cairo, Egypt",
                            PostedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "محاسب",
                            TitleEn = "Accountant"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "تم افتتاح محطة وقود جديدة في منطقة التجمع الخامس لخدمة سكان المنطقة بأعلى معايير الجودة.",
                            DescriptionEn = "A new fuel station has been opened in the Fifth Settlement area to serve residents with the highest quality standards.",
                            ImageUrl = "/images/news/new-station.jpg",
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "افتتاح محطة وقود جديدة",
                            TitleEn = "New Fuel Station Opening"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "تم تحديث أسعار الوقود وفقاً للأسعار العالمية. الأسعار الجديدة سارية من اليوم.",
                            DescriptionEn = "Fuel prices have been updated according to global prices. New prices are effective from today.",
                            ImageUrl = "/images/news/prices-update.jpg",
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "تحديث أسعار الوقود",
                            TitleEn = "Fuel Prices Update"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "توقيع اتفاقية شراكة استراتيجية مع كبرى شركات الطاقة لتوسيع نطاق خدماتنا.",
                            DescriptionEn = "Signing a strategic partnership agreement with major energy companies to expand our services.",
                            ImageUrl = "/images/news/partnership.jpg",
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TitleAr = "شراكة استراتيجية جديدة",
                            TitleEn = "New Strategic Partnership"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "وقود عالي الجودة بمعايير عالمية لجميع أنواع المركبات",
                            DescriptionEn = "High-quality fuel with international standards for all vehicle types",
                            IconUrl = "/images/services/premium-fuel.svg",
                            TitleAr = "وقود ممتاز",
                            TitleEn = "Premium Fuel"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "خدمة غسيل سيارات احترافية بأحدث المعدات والتقنيات",
                            DescriptionEn = "Professional car wash service with the latest equipment and technologies",
                            IconUrl = "/images/services/car-wash.svg",
                            TitleAr = "غسيل السيارات",
                            TitleEn = "Car Wash"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "مصلى نظيف ومكيف للرجال والنساء مع مرافق وضوء",
                            DescriptionEn = "Clean air-conditioned prayer room for men and women with ablution facilities",
                            IconUrl = "/images/services/prayer-room.svg",
                            TitleAr = "مصلى",
                            TitleEn = "Prayer Room"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "متجر متكامل يوفر جميع احتياجاتك من المشروبات والوجبات الخفيفة",
                            DescriptionEn = "Convenience store offering all your beverage and snack needs",
                            IconUrl = "/images/services/mini-market.svg",
                            TitleAr = "ميني ماركت",
                            TitleEn = "Mini Market"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "قهوة طازجة ومشروبات ساخنة وباردة لراحتك أثناء الرحلة",
                            DescriptionEn = "Fresh coffee and hot/cold beverages for your comfort during the journey",
                            IconUrl = "/images/services/coffee-shop.svg",
                            TitleAr = "كوفي شوب",
                            TitleEn = "Coffee Shop"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "حمامات نظيفة ومعقمة على مدار الساعة مع خدمات صيانة مستمرة",
                            DescriptionEn = "Clean and sanitized restrooms 24/7 with continuous maintenance services",
                            IconUrl = "/images/services/restrooms.svg",
                            TitleAr = "دورات مياه نظيفة",
                            TitleEn = "Clean Restrooms"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "أسعار ثابتة وشفافة معتمدة من الجهات الرسمية",
                            DescriptionEn = "Fixed and transparent prices approved by official authorities",
                            IconUrl = "/images/services/fixed-prices.svg",
                            TitleAr = "أسعار ثابتة",
                            TitleEn = "Fixed Prices"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "طرق دفع متعددة وآمنة: نقدي، بطاقات ائتمان، مدى، Apple Pay",
                            DescriptionEn = "Multiple secure payment methods: Cash, Credit Cards, Mada, Apple Pay",
                            IconUrl = "/images/services/secure-payment.svg",
                            TitleAr = "خيارات دفع آمنة",
                            TitleEn = "Secure Payment Options"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "أعلى معايير الأمان والسلامة مع شهادات جودة معتمدة",
                            DescriptionEn = "Highest safety standards with certified quality assurance",
                            IconUrl = "/images/services/safety-quality.svg",
                            TitleAr = "الأمان والجودة",
                            TitleEn = "Safety & Quality"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "فريق خدمة عملاء محترف متاح على مدار الساعة لخدمتكم",
                            DescriptionEn = "Professional customer service team available 24/7 to serve you",
                            IconUrl = "/images/services/customer-service.svg",
                            TitleAr = "خدمة العملاء",
                            TitleEn = "Customer Service"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "خدمة نفخ الإطارات مجاناً مع فحص ضغط الهواء",
                            DescriptionEn = "Free tire inflation service with air pressure check",
                            IconUrl = "/images/services/tire-air.svg",
                            TitleAr = "هواء للإطارات",
                            TitleEn = "Tire Air Service"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "خدمة تغيير زيت المحرك بزيوت أصلية عالية الجودة",
                            DescriptionEn = "Engine oil change service with genuine high-quality oils",
                            IconUrl = "/images/services/oil-change.svg",
                            TitleAr = "تغيير زيت",
                            TitleEn = "Oil Change"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "صراف آلي متاح على مدار الساعة لسحب النقود",
                            DescriptionEn = "ATM machine available 24/7 for cash withdrawal",
                            IconUrl = "/images/services/atm.svg",
                            TitleAr = "صراف آلي ATM",
                            TitleEn = "ATM Machine"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "إنترنت لاسلكي مجاني عالي السرعة لجميع الزوار",
                            DescriptionEn = "Free high-speed wireless internet for all visitors",
                            IconUrl = "/images/services/wifi.svg",
                            TitleAr = "واي فاي مجاني",
                            TitleEn = "Free WiFi"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "طريق الملك فهد، الرياض",
                            City = "Riyadh",
                            Country = "Saudi Arabia",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة وقود متكاملة الخدمات مع مصلى وميني ماركت وكوفي شوب",
                            DescriptionEn = "Full-service fuel station with prayer room, mini market, and coffee shop",
                            Latitude = 24.7136,
                            Longitude = 46.6753,
                            Phone = "+966 11 1234567",
                            TitleAr = "محطة السديس",
                            TitleEn = "Al-Sudais Station"
                        },
                        new
                        {
                            Id = 2,
                            Address = "طريق الملك عبدالعزيز، جدة",
                            City = "Jeddah",
                            Country = "Saudi Arabia",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة حديثة مع جميع الخدمات المتميزة وغسيل سيارات",
                            DescriptionEn = "Modern station with all premium services and car wash",
                            Latitude = 21.485800000000001,
                            Longitude = 39.192500000000003,
                            Phone = "+966 12 2345678",
                            TitleAr = "محطة الحركاني",
                            TitleEn = "Al-Harkani Station"
                        },
                        new
                        {
                            Id = 3,
                            Address = "حي النسيم، الرياض",
                            City = "Riyadh",
                            Country = "Saudi Arabia",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة وقود في حي النسيم مع كافة الخدمات",
                            DescriptionEn = "Fuel station in Al-Naseem district with all services",
                            Latitude = 24.6877,
                            Longitude = 46.756999999999998,
                            Phone = "+966 11 3456789",
                            TitleAr = "محطة النسيم",
                            TitleEn = "Al-Naseem Station"
                        },
                        new
                        {
                            Id = 4,
                            Address = "حي العاليات، المدينة المنورة",
                            City = "Madinah",
                            Country = "Saudi Arabia",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة متكاملة في منطقة العاليات مع مصلى ومتجر",
                            DescriptionEn = "Integrated station in Al-Aliyat area with prayer room and store",
                            Latitude = 24.467199999999998,
                            Longitude = 39.602400000000003,
                            Phone = "+966 14 4567890",
                            TitleAr = "محطة العاليات",
                            TitleEn = "Al-Aliyat Station"
                        },
                        new
                        {
                            Id = 5,
                            Address = "طريق المطار، الدمام",
                            City = "Dammam",
                            Country = "Saudi Arabia",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة وقود بالقرب من المطار مع خدمات سريعة",
                            DescriptionEn = "Fuel station near the airport with quick services",
                            Latitude = 26.4207,
                            Longitude = 50.088799999999999,
                            Phone = "+966 13 5678901",
                            TitleAr = "محطة الجوية",
                            TitleEn = "Al-Jawiya Station"
                        },
                        new
                        {
                            Id = 6,
                            Address = "طريق الملك سعود، الرس",
                            City = "Al-Rass",
                            Country = "Saudi Arabia",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "محطة وقود رئيسية في مدينة الرس مع جميع الخدمات",
                            DescriptionEn = "Main fuel station in Al-Rass city with all services",
                            Latitude = 25.866700000000002,
                            Longitude = 43.5,
                            Phone = "+966 16 6789012",
                            TitleAr = "محطة الرس",
                            TitleEn = "Al-Rass Station"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.SuccessPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SuccessPartners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريك استراتيجي في توريد الوقود",
                            DescriptionEn = "Strategic partner in fuel supply",
                            LogoUrl = "/images/partners/npc-logo.png",
                            TitleAr = "شركة البترول الوطنية",
                            TitleEn = "National Petroleum Company"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريك في مشاريع الطاقة المستدامة",
                            DescriptionEn = "Partner in sustainable energy projects",
                            LogoUrl = "/images/partners/rec-logo.png",
                            TitleAr = "شركة الطاقة المتجددة",
                            TitleEn = "Renewable Energy Co"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريك مالي واستثماري",
                            DescriptionEn = "Financial and investment partner",
                            LogoUrl = "/images/partners/ib-logo.png",
                            TitleAr = "بنك الاستثمار",
                            TitleEn = "Investment Bank"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionAr = "شريك في خدمات النقل واللوجستيات",
                            DescriptionEn = "Partner in transport and logistics services",
                            LogoUrl = "/images/partners/itc-logo.png",
                            TitleAr = "شركة النقل الدولية",
                            TitleEn = "International Transport Co"
                        });
                });

            modelBuilder.Entity("gLiter.Core.Models.TransportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TransportRequests");
                });

            modelBuilder.Entity("gLiter.Core.Models.TransportRequestImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransportRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TransportRequestId");

                    b.ToTable("TransportRequestImages");
                });

            modelBuilder.Entity("gLiter.Core.Models.TransportRequestImage", b =>
                {
                    b.HasOne("gLiter.Core.Models.TransportRequest", "TransportRequest")
                        .WithMany("Images")
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportRequest");
                });

            modelBuilder.Entity("gLiter.Core.Models.TransportRequest", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
