using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using gLiter.Core.Interfaces;
using gLiter.Core.Models;
using gLiter.Service.DTOs;
using gLiter.Service.Interfaces;

namespace gLiter.Service.Services;

public class GalleryService : IGalleryService
{
    private readonly IGalleryRepository _repository;
    private readonly IMapper _mapper;

    public GalleryService(IGalleryRepository repository, IMapper mapper)
    {
        _repository = repository;
        _mapper = mapper;
    }

    public async Task<PagedResponse<GalleryDto>> GetGalleryAsync(string lang, int pageNumber, int pageSize)
    {
        var result = await _repository.GetPagedAsync(pageNumber, pageSize);
        var mapped = result.Items.Select(e => MapToDto(e, lang)).ToList();
        return PagedResponse<GalleryDto>.Ok(mapped, pageNumber, pageSize, result.TotalCount);
    }

    public async Task<ApiResponse<GalleryDto>> GetByIdAsync(int id, string lang)
    {
        var entity = await _repository.GetByIdAsync(id);
        if (entity == null)
        {
            return ApiResponse<GalleryDto>.Fail("Gallery item not found");
        }

        return ApiResponse<GalleryDto>.Ok(MapToDto(entity, lang));
    }

    public async Task<ApiResponse<GalleryDto>> CreateAsync(GalleryDto dto)
    {
        var entity = _mapper.Map<GalleryImage>(dto);
        entity.Id = 0; // ensure identity column is generated by DB
        entity.CreatedAt = DateTime.UtcNow;
        var created = await _repository.AddAsync(entity);
        return ApiResponse<GalleryDto>.Ok(MapToDto(created, "en"), "Gallery item created");
    }

    public async Task<ApiResponse<GalleryDto>> UpdateAsync(int id, GalleryDto dto)
    {
        var entity = await _repository.GetByIdAsync(id);
        if (entity == null)
        {
            return ApiResponse<GalleryDto>.Fail("Gallery item not found");
        }

        entity.TitleAr = dto.TitleAr;
        entity.TitleEn = dto.TitleEn;
        entity.DescriptionAr = dto.DescriptionAr;
        entity.DescriptionEn = dto.DescriptionEn;
        entity.ImageUrl = dto.ImageUrl;
        await _repository.UpdateAsync(entity);

        return ApiResponse<GalleryDto>.Ok(MapToDto(entity, "en"), "Gallery item updated");
    }

    public async Task<ApiResponse<bool>> DeleteAsync(int id)
    {
        await _repository.DeleteAsync(id);
        return ApiResponse<bool>.Ok(true, "Gallery item deleted");
    }

    private GalleryDto MapToDto(GalleryImage entity, string lang)
    {
        var dto = _mapper.Map<GalleryDto>(entity);
        dto.Title = GetLocalized(entity.TitleAr, entity.TitleEn, lang);
        dto.Description = GetLocalized(entity.DescriptionAr, entity.DescriptionEn, lang);
        return dto;
    }

    private static string GetLocalized(string ar, string en, string lang) => string.Equals(lang, "ar", System.StringComparison.OrdinalIgnoreCase) ? ar : en;
}
